### ISSUE TITLE
"IF" after "ELSE" not syntax highlighted correctly in VS Code.

### ISSUE THREAD

**Issue by weaversam8** [earthly/earthfile-grammar#5]
The [earthly docs][0] show how a user can use an `IF` statement after an `ELSE` statement in an Earthfile, but the IF does not syntax highlight correctly in VS code in this scenario. Here is an image:

![Image shows example of improper syntax highlighting.](https://github.com/earthly/earthfile-grammar/assets/2546219/00e5df28-381a-4fdb-89c8-f7c45994b972)

Notice that the second `IF` is displayed in white, rather than the orange expected.

[0]: https://docs.earthly.dev/docs/earthfile#if

**Comment by idodod** [comment]
Hey @weaversam8 , thanks for creating this issue.
This is now part of version 0.0.16
